spring:
  application:
    name: zuul-server
server:
  port: 8762
eureka:
  instance:
    securePortEnabled: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka